package com.carmen.app.entities;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import javax.json.bind.annotation.JsonbTransient;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;





@Entity

public class Brand implements Serializable{

	
	private static final long serialVersionUID = 1L;

	@Id

	@NotNull(message = "Id is required")
	private String id;
	
	
	@NotNull(message = "Name is required")
	private String brandName;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "brand", cascade = CascadeType.ALL, orphanRemoval = true)
	@JsonbTransient
	private Set<Car> cars = new HashSet<Car>();
	
	public Brand() {
		
	}
	
	public String getId() {
		return id;
	}


	public void setId(String id) {
		this.id = id;
	}


	public String getBrandName() {
		return brandName;
	}


	public void setBrandName(String brandName) {
		this.brandName = brandName;
	}
	
	

	public Set<Car> getCars() {
		return cars;
	}

	public void setCars(Set<Car> cars) {
		this.cars = cars;
	}

	@PrePersist
	private void autoGeneratedId() {
		this.id = UUID.randomUUID().toString();
	}
	
	
	
}
